matrix:
  include:
  - name: "Java Tests"
    language: java
    jdk: oraclejdk8
    before_script:
      - export COVERALLS_PARALLEL=true
    install:
      - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    after_success:
      - mvn clean test cobertura:cobertura jacoco:report coveralls:report -DserviceName="travis-ci" -DserviceBuildNumber=$TRAVIS_BUILD_NUMBER

  - name: "Node/Javascript Tests"
    language: node_js
    node_js: "8"
    addons:
      chrome: stable
    before_script:
      - export DISPLAY=:99.0
      - export COVERALLS_PARALLEL=true
      - export CI_NAME="travis-ci"
      - export CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
      - sh -e /etc/init.d/xvfb start
      - npm start > /dev/null &
      - npm run update-webdriver
      - sleep 1 # give server time to start
      - grunt coverage-preprocess
    script:
      - npm run test-ci
      - grunt coverage

# Deploy Github pages after success of Java Tests.
deploy:
  provider: pages
  skip_cleanup: true
  keep-history: false
  target-branch: gh-pages
  github_token: "$GITHUB_TOKEN"
  local_dir: "./target/generated-docs"
  on:
    branch: sprint-tcdl-2-b03906-initial-documentation
    condition: $TRAVIS_JOB_NAME = "Java Tests"

# Send final notification to coveralls after all jobs have been completed.
notifications:
  webhooks:
    urls:
      - https://coveralls.io/webhook
