name: Build SAGE Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Get app version from package.json
      run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

    - name: Extract short commit hash
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Construct full image tag
      run: echo "FULL_IMAGE_TAG=harbor.library.tamu.edu/tomcatapps/sage:${{ env.VERSION }}-${{ env.SHORT_SHA }}" >> $GITHUB_ENV
    
    - name: Build the Docker image
      run: docker image build . --file Dockerfile --tag ${{ env.FULL_IMAGE_TAG }}

    - name: List and verify the image
      run: docker image ls --format "{{.Repository}}:{{.Tag}}" | grep "${{ env.FULL_IMAGE_TAG }}"

    - name: Log in to Harbor using Robot Account
      run: echo "${{ secrets.HARBOR_ROBOT_TOKEN }}" | docker login harbor.library.tamu.edu -u "${{ secrets.HARBOR_ROBOT_USERNAME }}" --password-stdin

    - name: Push image to harbor
      run: docker image push ${{ env.FULL_IMAGE_TAG }}

    - name: Log out from harbor
      run: docker logout harbor.library.tamu.edu
    
    - name: Remove image from node
      run: docker image rm ${{ env.FULL_IMAGE_TAG }}
